function parameters = ValidateSVRLSMParameters(parameters)
% added v0.8 9/29/17
% prevents you from needing to specify all parameters, since it will fill
% in missing ones

% if parameters.method.mass_univariate
%     warndlg('Mass univariate LSM is not supported yet')
% end

required_parms = {}; %{'parmsfile'};
for p = 1 : numel(required_parms)
    curparm = required_parms{p};
    if ~isfield(parameters,curparm)
        msg = ['Obligatory parameters "' curparm '" is undefined. Halting execution of analysis.'];
        error(msg)
    end
end

allparms = {'svscaling', 100, ...
            'do_make_summary', true, ... % this should be set in the GUI in the future.
            'invert_p_map_flag',1,...
            'is_saved',1,...
            'analysis_name','Unnamed analysis', ...
            'analysis_out_path',pwd,...
            'useLibSVM',1,... % should add a check to see whether we have matlab available here...
            'lesionvolcorrection','Regress on Both',...
            'voxelwise_p',0.005, ...
            'clusterwise_p',0.05,...
            'PermNumVoxelwise',10000,...
            'PermNumClusterwise',10000,...
            'apply_covariates_to_behavior',0,...
            'apply_covariates_to_lesion',0,...
            'parallelize',0,...
            'SavePreThresholdedPermutations',0,...
            'SavePostVoxelwiseThresholdedPermutations',0,...
            'SavePostClusterwiseThresholdedPermutations',0,...
            'SavePermutationPData', 0, ... % for cfwer
            'SaveNullPMapsPreThresholding', 0, ... % for cfwer
            'SaveNullPMapsPostThresholding',0, ... % for cfwer
            'SavePermutationData',0,...
            'gui_version',0.0,... % unknown...
            'lesion_thresh',10, ... 
            'gamma',5,...
            'cost',30,...
            'DoPerformPermutationTesting',1, ...
            'control_variable_names',{}
            };

for p = 1 : 2 : numel(allparms)
    curparmname = allparms{p};
    default_value = allparms{p+1};
    if ~isfield(parameters,curparmname)
        parameters.(curparmname) = default_value;

        if ~isnumeric(default_value)
            default_value = num2str(default_value);
        end
        
        msg = ['Assigning default value of "' default_value '" to SVRLSM parameter "' curparmname '".'];
        %warning(msg)
    end
end